mc_dbt:
  outputs:
    dev:
      dataset: musicprojects_analytics
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /opt/airflow/mc_dbt/google_credentials.json
      location: US
      method: service-account
      priority: interactive
      project: musicprojects
      threads: 1
      type: bigquery
  target: dev
